### ISSUE TITLE
node-dht22 fails to install with npm

### ISSUE THREAD

**Issue by jonbattista** [heqian/DHTServer#2]
Hoi,
I've installed the bcm2835 lib, tested it with adafruit's python and it works, but I can't seem to figure out how to compile node-dht22. npm install fails because it tries to run "node-gyp rebuild" for node-dht22. Any help? Thanks

**Comment by heqian** [comment]
Could you post the console logs here?

**Comment by jonbattista** [comment]
I cannot seem to compile node-dht22. Running node server.js: 

node server.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'node-dht22'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/dht/server.js:7:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

Then running npm install in the clone folder:
~/dht $ npm install
|

> node-dht22@0.0.2 install /home/pi/dht/node_modules/node-dht22
> node-gyp rebuild

make: Entering directory '/home/pi/dht/node_modules/node-dht22/build'
  CXX(target) Release/obj.target/dht22/dht22.o
../dht22.cc:140:31: error: ‘Arguments’ does not name a type
 Handle<Value> ReadDHT22(const Arguments& args) {
                               ^
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../dht22.cc:17:
/home/pi/.node-gyp/4.2.1/include/node/v8.h: In function ‘v8::Handlev8::Value ReadDHT22(const int&)’:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:885:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../dht22.cc:141:15: error: within this context
   HandleScope scope;
               ^
../dht22.cc:144:11: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
   if(args.Length()>0 && args[0]->IsNumber())
           ^
../dht22.cc:144:31: error: invalid types ‘const int[int]’ for array subscript
   if(args.Length()>0 && args[0]->IsNumber())
                               ^
../dht22.cc:145:15: error: invalid types ‘const int[int]’ for array subscript
     pin=args[0]->Int32Value();
               ^
../dht22.cc:147:33: error: no matching function for call to ‘v8::Object::New()’
   Local<Object> obj=Object::New();
                                 ^
../dht22.cc:147:33: note: candidate is:
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../dht22.cc:17:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2933:24: note: static v8::Localv8::Object v8::Object::New(v8::Isolate_)
   static Local<Object> New(Isolate_ isolate);
                        ^
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2933:24: note:   candidate expects 1 argument, 0 provided
../dht22.cc:154:12: error: ‘New’ is not a member of ‘v8::String’
   obj->Set(String::New("state"),Number::New(state));
            ^
../dht22.cc:154:50: error: no matching function for call to ‘v8::Number::New(int&)’
   obj->Set(String::New("state"),Number::New(state));
                                                  ^
../dht22.cc:154:50: note: candidate is:
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../dht22.cc:17:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2486:24: note: static v8::Localv8::Number v8::Number::New(v8::Isolate_, double)
   static Local<Number> New(Isolate_ isolate, double value);
                        ^
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2486:24: note:   candidate expects 2 arguments, 1 provided
../dht22.cc:155:12: error: ‘New’ is not a member of ‘v8::String’
   obj->Set(String::New("humidity"),Number::New(humidity));
            ^
../dht22.cc:155:56: error: no matching function for call to ‘v8::Number::New(float&)’
   obj->Set(String::New("humidity"),Number::New(humidity));
                                                        ^
../dht22.cc:155:56: note: candidate is:
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../dht22.cc:17:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2486:24: note: static v8::Localv8::Number v8::Number::New(v8::Isolate_, double)
   static Local<Number> New(Isolate_ isolate, double value);
                        ^
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2486:24: note:   candidate expects 2 arguments, 1 provided
../dht22.cc:156:12: error: ‘New’ is not a member of ‘v8::String’
   obj->Set(String::New("temperature"),Number::New(temperature));
            ^
../dht22.cc:156:62: error: no matching function for call to ‘v8::Number::New(float&)’
   obj->Set(String::New("temperature"),Number::New(temperature));
                                                              ^
../dht22.cc:156:62: note: candidate is:
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../dht22.cc:17:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2486:24: note: static v8::Localv8::Number v8::Number::New(v8::Isolate_, double)
   static Local<Number> New(Isolate_ isolate, double value);
                        ^
/home/pi/.node-gyp/4.2.1/include/node/v8.h:2486:24: note:   candidate expects 2 arguments, 1 provided
../dht22.cc:158:16: error: ‘class v8::HandleScope’ has no member named ‘Close’
   return scope.Close(obj);
                ^
../dht22.cc: In function ‘void init(v8::Handlev8::Object)’:
../dht22.cc:165:16: error: ‘NewSymbol’ is not a member of ‘v8::String’
   exports->Set(String::NewSymbol("read"),
                ^
../dht22.cc:166:38: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handlev8::Value (&)(const int&))’
       FunctionTemplate::New(ReadDHT22)->GetFunction());
                                      ^
../dht22.cc:166:38: note: candidate is:
In file included from /home/pi/.node-gyp/4.2.1/include/node/node.h:42:0,
                 from ../dht22.cc:17:
/home/pi/.node-gyp/4.2.1/include/node/v8.h:4349:34: note: static v8::Localv8::FunctionTemplate v8::FunctionTemplate::New(v8::Isolate_, v8::FunctionCallback, v8::Localv8::Value, v8::Localv8::Signature, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/pi/.node-gyp/4.2.1/include/node/v8.h:4349:34: note:   no known conversion for argument 1 from ‘v8::Handlev8::Value(const int&) {aka v8::Localv8::Value(const int&)}’ to ‘v8::Isolate_’
../dht22.cc: In function ‘v8::Handlev8::Value ReadDHT22(const int&)’:
../dht22.cc:159:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
dht22.target.mk:86: recipe for target 'Release/obj.target/dht22/dht22.o' failed
make: **\* [Release/obj.target/dht22/dht22.o] Error 1
make: Leaving directory '/home/pi/dht/node_modules/node-dht22/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.14-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/dht/node_modules/node-dht22
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.1.14-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-dht22@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht22@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-dht22 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-dht22
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dht/npm-debug.log

**Comment by heqian** [comment]
The node version you are using is much higher than the one I use (v0.10.29, installed from the Raspbian repo). It seems when compiling node-dht22, it uses the library files from your node v4.2.1. Could you try uninstalling v4.2.1 and "apt-get install nodejs"?
